apiVersion: logging.kubesphere.io/v1alpha2
kind: FluentBit
metadata:
  name: fluent-bit
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/name: fluent-bit
  annotations:
    fluentbit.io/exclude: "true"
    logging.kubesphere.io/exclude: "true"
spec:
  image: kubesphere/fluent-bit:v1.8.3
  fluentBitConfigName: fluent-bit-config
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 25Mi
  positionDB:
    hostPath:
      path: /var/lib/fluent-bit/
  tolerations:
    - operator: Exists
