apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: containerd
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  systemd:
    tag: service.containerd
    path: /var/log/journal
    db: /fluent-bit/tail/docker.db
    dbSync: Normal
    systemdFilter:
    - _SYSTEMD_UNIT=containerd.service
